### ISSUE TITLE
New Vegas Cannot Launch

### ISSUE THREAD

**Issue by cprin21** [ralgar/proton-mo2-installer#8] opened 2022-08-05 10:45 UTC
From the Mod Organizer 2 user interface, launching NVSE leads to a popup saying "An instance of Mod Organizer is already running" instead of launching the game. This problem is occuring on Arch (EndeavourOS), and Ubuntu (Xubuntu).
This problem is not shared by Fallout 4 or TES4: Oblivion.

**Comment by ralgar** [comment] 2022-08-05 18:48
That's odd. Can you confirm the path to the NVSE executable, as set in MO2?

Also, did this happen before, with the older NVSE version from #6?

**Comment by cprin21** [comment] 2022-08-05 19:24
Tried 1.0.1, 1.0.0, and 1.0.0RC8 and all the same result. 
![Screenshot_2022-08-05_15-22-03](https://user-images.githubusercontent.com/107228497/183146895-3aff5f7c-8227-4e0b-81a2-df90fc3cbdbb.png)
![Screenshot_2022-08-05_15-22-03](https://user-images.githubusercontent.com/107228497/183146958-12239caa-9028-4abd-8b3a-091680fd0ab8.png)

**Comment by cprin21** [comment] 2022-08-05 19:26
Tried 1.0.1, 1.0.0, and 1.0.0RC8 and all the same result. 
![Screenshot_2022-08-05_15-22-03](https://user-images.githubusercontent.com/107228497/183147218-0a6df221-b6b3-4f0e-953c-72e9baf2518a.png)
![Screenshot_2022-08-05_15-22-03](https://user-images.githubusercontent.com/107228497/183147237-64c209e3-4f47-45cd-9287-4e57869c669c.png)

**Comment by cprin21** [comment] 2022-08-05 19:28
Tried 1.0.1, 1.0.0, and 1.0.0RC8 and all the same result. The problem is also Proton and xNVSE version agnostic on top of being an issue on all distros. (ignore the DE theming lol) (Also, again not a problem for other games set up with proton-mo2-installer - this issue is only happening to New Vegas)
![Screenshot_2022-08-05_15-22-03](https://user-images.githubusercontent.com/107228497/183147535-e3d00f49-6bbe-4c19-9788-43ddb669b2c4.png)
![Screenshot_2022-08-05_15-25-27](https://user-images.githubusercontent.com/107228497/183147543-ab167369-122b-439b-94d1-2eeb0e8fd149.png)

**Comment by ralgar** [comment] 2022-08-05 22:00
The file and directory structure looks to be the same as the other games, so there should be no problem there.

Are you using the [4GB patcher](https://www.nexusmods.com/newvegas/mods/62552)? I found [this thread](https://steamcommunity.com/app/22380/discussions/0/2952629277995656204) thread saying that you must use the `New Vegas` executable to launch the game if you are, and it will load NVSE automatically.

**Comment by cprin21** [comment] 2022-08-05 22:07
> Are you using the [4GB patcher](https://www.nexusmods.com/newvegas/mods/62552)? I found [this thread](https://steamcommunity.com/app/22380/discussions/0/2952629277995656204) thread saying that you must use the `New Vegas` executable to launch the game if you are, and it will load NVSE automatically.

This problem occurs whether or not I have the 4GB Patcher installed (the proton version in the files section). No idea what's causing this problem as I have been doing the same thing to New Vegas as I have my other Bethesda games. This only started happening yesterday and today but now it occurs whatever version of proton-mo2-installer I use to install MO2. In the screenshots above, I did not have the 4GB Patcher installed.

Also if it helps, selecting Fallout New Vegas or Fallout New Vegas Launcher also comes up with the "Mod Organizer is already running" pop up which I am assuming is as intended since this script basically overwrites those to launch MO2 but I think the issue is it may have overwritten xNVSE to do so as well perhaps.

**Comment by ralgar** [comment] 2022-08-05 22:23
This is really an odd one. The script only overwrites the Launcher executable. The `New Vegas` or `FalloutNV.exe` should still work as normal, like with the other games.

Can you send a detailed directory listing of the game dir? `ls -lah /path/to/game/dir`

**Comment by cprin21** [comment] 2022-08-05 22:32
> Can you send a detailed directory listing of the game dir? `ls -lah /path/to/game/dir`

Here is my output of that command.
```
total 46M
drwxr-xr-x 1 user user  712 Aug  5 18:27 .
drwxr-xr-x 1 user user  178 Aug  5 16:52 ..
-rwxr-xr-x 1 user user 162K Aug  5 18:16 atimgpud.dll
-rwxr-xr-x 1 user user 331K Aug  5 18:16 binkw32.dll
drwxr-xr-x 1 user user 1.7K Aug  5 18:27 Data
-rwxr-xr-x 1 user user  20K Aug  5 18:19 Fallout_default.ini
-rwxr-xr-x 1 user user  16M Aug  5 18:16 FalloutNV.exe
-rwxr-xr-x 1 user user 165K Aug  5 18:17 FalloutNV.ico
-rw-r--r-- 1 user user  75K Aug  5 18:27 FalloutNVLauncher.exe
-rwxr-xr-x 1 user user 2.0M Aug  5 18:19 FalloutNVLauncher.exe.bak
-rwxr-xr-x 1 user user 1.9M Aug  5 18:16 GDFFalloutNV.dll
-rwxr-xr-x 1 user user 1.1K Aug  5 18:16 high.ini
-rwxr-xr-x 1 user user  889 Aug  5 18:28 InstallScript.vdf
-rwxr-xr-x 1 user user 1.2M Aug  5 18:16 libvorbis.dll
-rwxr-xr-x 1 user user 118K Aug  5 18:16 libvorbisfile.dll
-rwxr-xr-x 1 user user 1.1K Aug  5 18:16 low.ini
-rwxr-xr-x 1 user user 5.9M Aug  5 18:16 MainTitle.wav
-rwxr-xr-x 1 user user 1.1K Aug  5 18:16 medium.ini
-rw-r--r-- 1 user user 1.1M Jul 20 12:53 nvse_1_4.dll
-rw-r--r-- 1 user user  16M Jul 20 12:53 nvse_1_4.pdb
-rw-r--r-- 1 user user 481K Jul 20 13:31 nvse_editor_1_4.dll
-rw-r--r-- 1 user user 282K May 13 16:34 nvse_loader.exe
-rw-r--r-- 1 user user 155K Apr 21 12:57 nvse_steam_loader.dll
-rw-r--r-- 1 user user   94 Aug  5 18:27 proton-shunt.cfg
-rwxr-xr-x 1 user user 4.0K Aug  5 18:19 Readme.txt
drwxr-xr-x 1 user user   46 Aug  5 18:20 Redists
-rwxr-xr-x 1 user user 120K Aug  5 18:16 steam_api.dll
-rwxr-xr-x 1 user user 1.2K Aug  5 18:16 VeryHigh.ini
```

**Comment by ralgar** [comment] 2022-08-05 22:48
Everything looks like it should:
- The NVSE DLL files are present.
- `nvse_loader.exe` is present and the correct size.
- proton-shunt has replaced `FalloutNVLauncher.exe`, we can tell by its small size of 75KB relative to the `.bak` file's size of 2.0MB
- `FalloutNV.exe` hasn't been replaced, we can tell by its large size of 16MB.
- All of the executables are unique in size, so none of them have overwritten anything they shouldn't.
- We can also tell by the permissions what files have been overwritten. Steam puts execute permissions (`x`) on all game files by default. The ones that don't have execute permissions are what have been modified by the script.

I'm not sure what to say. Unfortunately I don't have a copy of the game, so I can't reproduce this issue directly. My best suggestion right now is to uninstall New Vegas mod tools using the script, verify the game data in Steam, and then reinstall the mod tools again.

**Comment by cprin21** [comment] 2022-08-06 02:52
Reporting the same issue in Nobara Project Gnome (essentially Fedora). Launching xNVSE through MO2 installed either through here or (important to troubleshooting) also through Rockerbacon's modorganizer2-linux-installer project both causes a popup saying that Mod Organizer is already running. There's something launching MO2 instead of xNVSE launching FalloutNV.exe. Something must have broken outside of this project which sucks.

I'm also not doing anything wrong.
Making sure bsdtar is installed (it is by default on Arch, bsdtar on Fedora and libarchive-tools on Ubuntu)
Making sure Protontricks is installed (non Flatpak, on Ubuntu it requires using Pipx to install the recent version on top of the version installed through APT)
Making sure Steam is installed (non Flatpak)
Install New Vegas, launch, set settings
Run this script, set up MO2
xNVSE makes that popup instead of running

Ergo because it's across this and the other script and it wasn't the case before, it's either something wrong with bsdtar, Proton, protontricks, or Steam or any of their prerequisites or even Linux itself (doubtful since it's the kernel).

**Comment by cprin21** [comment] 2022-08-18 12:39
I would love to have Flatpak Steam become compatible with this install script as it would allow me to test whether or not New Vegas works with MO2 on Linux on Flatpak since it doesn't on the native version of Steam regardless of distro.

Currently it detects that the chosen game is indeed installed on Flatpak Steam, goes through everything, and then in the section for installing custom Proton, if native Steam is installed it will open that and try to install the selected game, and then either way if you have it installed or not the dialogue saying "installing custom Proton" will just stay there forever loading. I believe the script is trying to install the custom Proton to the native version instead of the Flatpak version even if the rest of the script is registering the Flatpak version of Steam. 
(I hope I've been helpful I really do need to just learn Python though in the long run haha)
Edit: Going to add this as a separate issue

**Comment by cprin21** [comment] 2022-09-25 19:18
IMPORTANT UPDATE:
The New Vegas not opening bug is due to the `compatdata` folder in `~/.local/share/Steam/steamapps/compatdata`.
New Vegas' `compatdata` folder is `22380` as that is its steamid. What was happening with me is there was a `compatdata` folder there for New Vegas despite the game not being installed, messing up the game once it is installed.

TO FIX:
Make sure New Vegas is uninstalled, proton-mo2-installer is uninstalled for New Vegas, and the Fallout New Vegas folder under `~/.local/share/Steam/steamapps/common` is deleted.
Delete the `22380` folder under `~/.local/share/Steam/steamapps/compatdata`.
Install New Vegas as normal, install proton-mo2-installer for New Vegas as normal.

**Comment by ralgar** [comment] 2022-09-26 17:57
Oh, that is super odd. I've never had an issue like that before with Steam/Proton.

Glad you were able to sort it out, and thanks for posting the fix! I'll close this issue now.

**Closed as completed by ralgar** 2022-09-26 17:57 UTC
Labels: bug
